#!/bin/bash
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

digitalocean=14061
google=15169
amazon1=14618
amazon2=16509
cloudflare=AS13335

function scan_asn()
{
    whois=($(whois -h whois.radb.net -- "-i origin AS$1" | grep -Eo "([0-9.]+){4}/[0-9]+"))
    j=256
    for((i=0; i < "${#whois[@]}"; i+=j))
    do
        range_list=("${whois[@]:i:j}")
        dotnet ${dir}/Bin/Release/Nerva.NodeFinder.dll ${range_list[@]}
    done

    #todo: after each run check for connections and quit if connected
}

echo "Digital Ocean"
scan_asn ${digitalocean}

echo "Scanning Google"
scan_asn ${google}

echo "Scanning Amazon"
scan_asn ${amazon1}
scan_asn ${amazon2}
