#!/bin/bash
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#curl --silent -X POST http://127.0.0.1:17566/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"add_peer","params":{"host":"206.81.2.15"}}' > /dev/null
#curl --silent -X POST http://127.0.0.1:17566/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"add_peer","params":{"host":"206.81.2.16"}}' > /dev/null

#exit 0

digitalocean=14061
google=15169
amazon1=14618
amazon2=16509
cloudflare=AS13335

function scan_asn()
{
    whois=($(whois -h whois.radb.net -- "-i origin AS$1" | grep -Eo "([0-9.]+){4}/[0-9]+"))
    j=1024
    for((i=0; i < "${#whois[@]}"; i+=j))
    do
        range_list=("${whois[@]:i:j}")
        dotnet ${dir}/Bin/Release/Nerva.NodeFinder.dll ${range_list[@]}
    done
}

echo "Digital Ocean"
scan_asn ${digitalocean}

echo "Scanning Google"
scan_asn ${google}

echo "Scanning Amazon"
scan_asn ${amazon1}
scan_asn ${amazon2}
