#!/bin/bash
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

scanner=${dir}/External/c-syn-scan-network/syn-scan-network
validator=${dir}/External/Nerva.Tools/Bin/Release/NodeValidator
touch ${dir}/nodelist

digitalocean=14061
verizon=6167

RED='\033[0;31m'
GREEN='\033[0;32m'
GRAY='\033[1;30m'
NC='\033[0m'

function scan_cidr()
{
    echo Thread $2 Scanning CIDR range $1
    hosts=($(prips $1))
    for host in "${hosts[@]}"
    do
        #echo -e ${GRAY}${host}${NC}
        ${scanner} $host 17565
        if [ $? -gt 0 ]; then
            echo Port open. Validating...
            ${validator} --host $host
            if [ $? == 1 ]; then
                echo -e ${GREEN}${host}${NC}
                echo $host >> ${dir}/nodelist
            else
                echo -e ${RED}${host}${NC}
            fi
        fi
    done
}

function scan_asn()
{
    local whois=($(whois -h whois.radb.net -- "-i origin AS$1" | grep -Eo "([0-9.]+){4}/[0-9]+"))
    local j=16
    local t=0
    for((i=0; i < "${#whois[@]}"; i+=j))
    do
        range_list=("${whois[@]:i:j}")
        for x in "${range_list[@]}"
        do
            scan_cidr $x $t &
            t=$((t+1))
        done
        wait
    done

    # crawl the node list to expand the results
}

scan_asn ${digitalocean}
