#!/bin/bash
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

validator=${dir}/Bin/Release/publish/NodeValidator
crawler=${dir}/Bin/Release/publish/NetworkCrawler
touch ${dir}/nodelist

digitalocean=14061

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

function scan_cidr()
{
    echo Scanning CIDR range $x
    hosts=($(prips $1))
    for host in "${hosts[@]}"
    do
        ${validator} --host $host &> /dev/null
        if [ $? == 1 ]; then
            echo -e ${GREEN}${host}${NC}
            echo $host >> ${dir}/nodelist
        else
            echo -e ${RED}${host}${NC}
        fi
    done
}

function scan_asn()
{
    whois=($(whois -h whois.radb.net -- "-i origin AS$1" | grep -Eo "([0-9.]+){4}/[0-9]+"))
    j=256
    counter=0
    for((i=0; i < "${#whois[@]}"; i+=j))
    do
        range_list=("${whois[@]:i:j}")
        for x in "${range_list[@]}"
        do
            scan_cidr $x &
            ((counter++))

            if [ "$counter" -gt 40 ];then
                wait
                echo "Resetting batch counter"
                counter=0
            fi
        done
    done

    # crawl the node list to expand the results
}

scan_asn ${digitalocean}